/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAiTeamRouteImport } from './routes/dashboard.ai-team'
import { Route as DashboardFounderRouteImport } from './routes/dashboard.founder'
import { Route as DashboardInvestorRouteImport } from './routes/dashboard.investor'
import { Route as DashboardJourneyRouteImport } from './routes/dashboard.journey'
import { Route as DashboardMentorRouteImport } from './routes/dashboard.mentor'
import { Route as DashboardRegistrationRouteImport } from './routes/dashboard.registration'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiTeamRoute = DashboardAiTeamRouteImport.update({
  id: '/ai-team',
  path: '/ai-team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFounderRoute = DashboardFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvestorRoute = DashboardInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJourneyRoute = DashboardJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMentorRoute = DashboardMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrationRoute = DashboardRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ai-team': typeof DashboardAiTeamRoute
  '/dashboard/founder': typeof DashboardFounderRoute
  '/dashboard/investor': typeof DashboardInvestorRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/registration': typeof DashboardRegistrationRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/ai-team': typeof DashboardAiTeamRoute
  '/dashboard/founder': typeof DashboardFounderRoute
  '/dashboard/investor': typeof DashboardInvestorRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/registration': typeof DashboardRegistrationRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ai-team': typeof DashboardAiTeamRoute
  '/dashboard/founder': typeof DashboardFounderRoute
  '/dashboard/investor': typeof DashboardInvestorRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/registration': typeof DashboardRegistrationRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/ai-team'
    | '/dashboard/founder'
    | '/dashboard/investor'
    | '/dashboard/journey'
    | '/dashboard/mentor'
    | '/dashboard/registration'
    | '/dashboard/student'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/ai-team'
    | '/dashboard/founder'
    | '/dashboard/investor'
    | '/dashboard/journey'
    | '/dashboard/mentor'
    | '/dashboard/registration'
    | '/dashboard/student'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/ai-team'
    | '/dashboard/founder'
    | '/dashboard/investor'
    | '/dashboard/journey'
    | '/dashboard/mentor'
    | '/dashboard/registration'
    | '/dashboard/student'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-team': {
      id: '/dashboard/ai-team'
      path: '/ai-team'
      fullPath: '/dashboard/ai-team'
      preLoaderRoute: typeof DashboardAiTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/founder': {
      id: '/dashboard/founder'
      path: '/founder'
      fullPath: '/dashboard/founder'
      preLoaderRoute: typeof DashboardFounderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/investor': {
      id: '/dashboard/investor'
      path: '/investor'
      fullPath: '/dashboard/investor'
      preLoaderRoute: typeof DashboardInvestorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/journey': {
      id: '/dashboard/journey'
      path: '/journey'
      fullPath: '/dashboard/journey'
      preLoaderRoute: typeof DashboardJourneyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mentor': {
      id: '/dashboard/mentor'
      path: '/mentor'
      fullPath: '/dashboard/mentor'
      preLoaderRoute: typeof DashboardMentorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registration': {
      id: '/dashboard/registration'
      path: '/registration'
      fullPath: '/dashboard/registration'
      preLoaderRoute: typeof DashboardRegistrationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiTeamRoute: typeof DashboardAiTeamRoute
  DashboardFounderRoute: typeof DashboardFounderRoute
  DashboardInvestorRoute: typeof DashboardInvestorRoute
  DashboardJourneyRoute: typeof DashboardJourneyRoute
  DashboardMentorRoute: typeof DashboardMentorRoute
  DashboardRegistrationRoute: typeof DashboardRegistrationRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiTeamRoute: DashboardAiTeamRoute,
  DashboardFounderRoute: DashboardFounderRoute,
  DashboardInvestorRoute: DashboardInvestorRoute,
  DashboardJourneyRoute: DashboardJourneyRoute,
  DashboardMentorRoute: DashboardMentorRoute,
  DashboardRegistrationRoute: DashboardRegistrationRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
